# site settings
title: Biz Apps
subtitle: Company
email: contact@bizapps.dev
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 206/47 Porter Street
city: Prahran
state: VIC
zip_code: 3181
country: Australia
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/bizappsco
github_url: https://github.com/bizappsco
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/company/bizappsco
pinterest_url:
slack_url:
twitter_url: https://twitter.com/bizappsco

# build settings
markdown: kramdown

sass:
  style: compressed
